1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [1]:
import numpy as np

In [31]:
a = np.array([[-1, -6],
              [2, 6]])
i = np.array([[1, 0],
             [0, 1]])
# Решаем квадратное уравнение lamb^2 - 5*lamb + 6 = 0
lamb1 = 3
lamb2 = 2
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


2. Дан оператор поворота на 180 градусов, задаваемый матрицей. Показать, что любой вектор является для него собственным.

In [33]:
b = np.array([[-1, 0], 
              [0, -1]])
z = np.array([1, 10])
la = np.dot(b, z)
print(la)
w1, v1 = np.linalg.eig(b)
print(f'Матрица A:\n{b}')
print(f'Собственные значения:\n{w1}')
print(f'Собственные векторы:\n{v1}')

[ -1 -10]
Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


3. Пусть линейный оператор задан матрицей. Установить, является ли вектор  𝑥=(1,1)  собственным вектором этого линейного оператора.

In [9]:
c = np.array([[1, 1], 
              [-1, 3]])
x = np.array([1, 1])
l = np.dot(c, x)
l / x
# Вектор является собственным lambda = 2 

array([2., 2.])

4. Пусть линейный оператор задан матрицей. Установить, является ли вектор  𝑥=(3,−3,−4)  собственным вектором этого линейного оператора.

In [24]:
d = np.array([[0, 3, 0], 
              [3, 0, 0], 
              [0, 0, 3]])
y = np.array([3, -3, -4])
lam = np.dot(d, y)
print(lam)
np.divide(lam, y)
# Вектор не является собственным.

[ -9   9 -12]


array([-3., -3.,  3.])