#### Практическое задание 1

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:  

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ; Неопределена.    

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ; Размерность 2 х 3 

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ; Размерность 8 х 8   

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 Размерность 4 х 4

In [1]:
import numpy as np

2. Найти сумму и произведение матриц

In [18]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц\n {a + b}\n Произведение матриц\n {a * b}')

Сумма матриц
 [[ 5 -3]
 [ 3  5]]
 Произведение матриц
 [[4 2]
 [0 0]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство.   
Вычислить линейную комбинацию  
3𝐴−2𝐵+4𝐶  
для матриц  

In [19]:
a1 = np.array([[1, 7], [3, -6]])
b1 = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3*a1 - 2*b1 + 4*c

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица  𝐴 . Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [80]:
a2 = np.array([[4, 1], [5, -2], [2, 3]])
AAT = np.dot(a2, a2.T)
ATA = np.dot(a2.T, a2)
print("AAT\n", AAT)
print("ATA\n", ATA)

AAT
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
ATA
 [[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [78]:
a3 = [[1, 2, 3]]
b3 = [[1, 2], [4, 5], [7, 8]]
an = np.array(a3)
bn = np.array(b3)
ab = np.dot(a3, b3)
print("Проверка numpy\n", ab)
def dot_matrix(a, b):
    if len(a[0]) != len(b):
        print('Размерность матриц не подходит для умножения')
        return 0
    c = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(c)):
        for j in range(len(c[0])):
            for l in range(len(b)):
                c[i][j] += a[i][l]*b[l][j]
    print("Решение ", c)
dot_matrix(a3, b3)

Проверка numpy
 [[30 36]]
Решение  [[30, 36]]


#### Практическое задание 2

1. Вычислить определитель:  

a)

|sinx  -cosx|  
|cosx   sinx  |

Определитель равен sinx ** 2 + cosx ** 2 = 1

б)

In [81]:
d = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(d)

180.0

в)

In [82]:
e = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(e)

-9.51619735392994e-16

2. Определитель матрицы  𝐴  равен  4 . Найти:  

а)  𝑑𝑒𝑡(𝐴2) = 16;  

б)  𝑑𝑒𝑡(𝐴𝑇) = 4;  

в)  𝑑𝑒𝑡(2𝐴) Не определить, поскольку не известен размер матрицы.

3. Доказать, что матрица вырожденная.

In [86]:
f = np.array([[-2, 7, -3], 
              [4, -14, 6], 
              [-3, 7, 13]])
np.linalg.inv(f)

LinAlgError: Singular matrix

Первая и вторая строки линейно зависимые.

4. Найти ранг матрицы:

а)

In [83]:
g = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(g)

2

б)

In [84]:
h = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(h)

3