1. Решить систему уравнений методом Гаусса:

𝑥1+𝑥2−𝑥3−2 * 𝑥4=0,  
2 * 𝑥1+𝑥2−𝑥3+𝑥4=−2,  
𝑥1+𝑥2−3 * 𝑥3+𝑥4=4.  

In [1]:
import numpy as np

In [638]:
# Матрица для примера из урока
ab = np.array([[2.0, 1.0, 1.0, 5.0],
             [4.0, -6.0, 0.0, -2.0],
             [-2.0, 7.0, 2.0, 9.0]])

In [639]:
def linear_equation_system(a):
    # Разделим расширенную матрицу на две
    b = np.copy(a[:,:-1])
    print('Матрица коэффициэнтов')
    print(b)
    c = np.copy(a[:,-1:].T[0])
    print('Свободные члены')
    print(c)
    # Проверим условия существования решений
    rank_b = np.linalg.matrix_rank(b)
    rank_a = np.linalg.matrix_rank(a)
    if rank_a == rank_b and rank_a == len(b[0]):
        print('Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и количеству переменных.\nПо теореме Кронекера-Капелии имеется 1 решение.')
    elif rank_a == rank_b and rank_a < len(b[0]):
        print('Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и меньше количества переменных.\nПо теореме Кронекера-Капелии имеется бесконечное количество решений.')
    elif rank_b < rank_a:
        print('Ранг матрицы коэффициэнтов меньше ранга расширенной матрицы.\nПо теореме Кронекера-Капелии система не совместна.')
    elif rank_b == len(b[0]) and c == 0:
        x = [0 for i in range(len(b[0]))]
        print('Однородная система имеет только тривиальные решения')
        return b, c, x
    if np.linalg.det(b) == 0 or a[0][0] == 0:
        print('Система решения не имеет')
        return 0, 0, 0
    print('Расширенная матрица системы')
    print(a)
    # Преобразуем матрицу в верхнюю треугольную
    for i in range(len(a)-1):
        for j in range(i+1, len(a)):
            k = a[j][i] / a[i][i]
            for n in range(len(a[0])):
                a[j][n] = a[j][n] - a[i][n] * k
            
    print('Преобразованная матрица')        
    print(a)
    # Находим корни
    x = []
    for i in range(len(a)-1, -1, -1):
        if len(x) > 0:
            for n in range(len(x)):
                a[i][-1] = a[i][-1] - a[i][-2-n] * x[n-1]
        if a[i][i] == 0 and a[i][-1] == 0:
            print('Система имеет бесконечное множество решений')
            return 1, 1, 1
        elif a[i][i] == 0 and a[i][-1] != 0:
            print('Система решений не имеет')
            return 0, 0, 0
        xn = a[i][-1] / a[i][i]
        x.append(xn)
    x.reverse()
    print('Результат')
    print(x)
    return b, c, x

In [620]:
# Проверка
def check(b, c, x):
#     print('Проверка')
#     print(c)
#     print('*'*10)
#     print(b)
#     print('*'*10)
#     print(x)
#     print('*'*10)
    for i in range(len(x)):
        k = b[i] * x
        s = 0
        for j in range(len(k)):
            s += k[j]
        print(c[i], '=', s)
    print('*'*10)

In [621]:
b, c, x = linear_equation_system(ab)

Матрица коэффициэнтов
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]
Свободные члены
[ 5. -2.  9.]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и количеству переменных.
По теореме Кронекера-Капелии имеется 1 решение.
Расширенная матрица системы
[[ 2.  1.  1.  5.]
 [ 4. -6.  0. -2.]
 [-2.  7.  2.  9.]]
Преобразованная матрица
[[  2.   1.   1.   5.]
 [  0.  -8.  -2. -12.]
 [  0.   0.   1.   2.]]
Результат
[1.0, 1.0, 2.0]


In [622]:
check(b, c, x)

5.0 = 5.0
-2.0 = -2.0
9.0 = 9.0
**********


In [623]:
a = np.array([[1.0, 1.0, -1.0, -2.0, 0.0],
             [2, 1, -1, 1, -2],
             [1, 1, -3, 1, 4],
             [0, 0, 0, 0, 0]])

In [624]:
linear_equation_system(a)

Матрица коэффициэнтов
[[ 1.  1. -1. -2.]
 [ 2.  1. -1.  1.]
 [ 1.  1. -3.  1.]
 [ 0.  0.  0.  0.]]
Свободные члены
[ 0. -2.  4.  0.]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и меньше количества переменных.
По теореме Кронекера-Капелии имеется бесконечное количество решений.
Система решения не имеет


(0, 0, 0)

Систему решить не смог, поскольку нейзвестных 3, а уравнения 4.

2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

a)  

𝑥1−2 * 𝑥2=13  
𝑥1−4 * 𝑥2=7

In [625]:
a1 = np.array([[1, -2, 13],
              [1, -4, 7]])

In [626]:
b1, c1, x1 = linear_equation_system(a1)

Матрица коэффициэнтов
[[ 1 -2]
 [ 1 -4]]
Свободные члены
[13  7]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и количеству переменных.
По теореме Кронекера-Капелии имеется 1 решение.
Расширенная матрица системы
[[ 1 -2 13]
 [ 1 -4  7]]
Преобразованная матрица
[[ 1 -2 13]
 [ 0 -2 -6]]
Результат
[19.0, 3.0]


In [627]:
check(b1, c1, x1)

13 = 13.0
7 = 7.0
**********


Система имеет решение, значит совместна.

б)  
 
2 * 𝑥1 − 𝑥2 + 5 * 𝑥3 = 10

𝑥1 + 𝑥2 − 3 * 𝑥3 = −2  

2 * 𝑥1 + 4 * 𝑥2 + 𝑥3 = 1

In [628]:
a2 = np.array([[2.0, -1.0, 5.0, 10.0],
              [1.0, 1.0, -3.0, -2.0],
              [2.0, 4.0, 1.0, 1.0]])

In [629]:
b2, c2, x2 = linear_equation_system(a2)

Матрица коэффициэнтов
[[ 2. -1.  5.]
 [ 1.  1. -3.]
 [ 2.  4.  1.]]
Свободные члены
[10. -2.  1.]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и количеству переменных.
По теореме Кронекера-Капелии имеется 1 решение.
Расширенная матрица системы
[[ 2. -1.  5. 10.]
 [ 1.  1. -3. -2.]
 [ 2.  4.  1.  1.]]
Преобразованная матрица
[[ 2.         -1.          5.         10.        ]
 [ 0.          1.5        -5.5        -7.        ]
 [ 0.          0.         14.33333333 14.33333333]]
Результат
[8.0, -1.0, 1.0]


In [630]:
check(b2, c2, x2)

10.0 = 22.0
-2.0 = 4.0
1.0 = 13.0
**********


Странный результат

в)  
𝑥1 + 2 * 𝑥2 + 5 * 𝑥3 = 4  

3 * 𝑥1 + 𝑥2 − 8 * 𝑥3 = −2

In [631]:
a3 = np.array([[1.0, 2.0, 5.0, 4.0],
              [3.0, 1.0, -8.0, -2.0],
              [0, 0, 0, 0]])

In [632]:
b3, c3, x3 = linear_equation_system(a3)

Матрица коэффициэнтов
[[ 1.  2.  5.]
 [ 3.  1. -8.]
 [ 0.  0.  0.]]
Свободные члены
[ 4. -2.  0.]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и меньше количества переменных.
По теореме Кронекера-Капелии имеется бесконечное количество решений.
Система решения не имеет


3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

In [633]:
a4 = np.array([[1.0, 3.0, -2.0, 4.0, 3.0],
              [0, 5, 0, 1, 2],
              [0, 0, 3, 0, 4],
              [0, 0, 0, 2, 1]])

In [634]:
b4, c4, x4 = linear_equation_system(a4)

Матрица коэффициэнтов
[[ 1.  3. -2.  4.]
 [ 0.  5.  0.  1.]
 [ 0.  0.  3.  0.]
 [ 0.  0.  0.  2.]]
Свободные члены
[3. 2. 4. 1.]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и количеству переменных.
По теореме Кронекера-Капелии имеется 1 решение.
Расширенная матрица системы
[[ 1.  3. -2.  4.  3.]
 [ 0.  5.  0.  1.  2.]
 [ 0.  0.  3.  0.  4.]
 [ 0.  0.  0.  2.  1.]]
Преобразованная матрица
[[ 1.  3. -2.  4.  3.]
 [ 0.  5.  0.  1.  2.]
 [ 0.  0.  3.  0.  4.]
 [ 0.  0.  0.  2.  1.]]
Результат
[-0.5333333333333332, 0.13333333333333336, 1.3333333333333333, 0.5]


In [635]:
check(b4, c4, x4)

3.0 = -0.7999999999999998
2.0 = 1.1666666666666667
4.0 = 4.0
1.0 = 1.0
**********


Странное решение.

4. Дана система линейных уравнений, заданная расширенной матрицей. Найти соотношение между параметрами  𝑎 ,  𝑏  и  𝑐 , при которых система является несовместной.

In [636]:
a5 = np.array([[1, 2, 3, 0],
               [4, 5, 6, 0],
               [7, 8, 9, 0]])

In [637]:
b5, c5, x5 = linear_equation_system(a5)

Матрица коэффициэнтов
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Свободные члены
[0 0 0]
Ранг матрицы коэффициэнтов равен рангу расширенной матрицы и меньше количества переменных.
По теореме Кронекера-Капелии имеется бесконечное количество решений.
Расширенная матрица системы
[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
Преобразованная матрица
[[ 1  2  3  0]
 [ 0 -3 -6  0]
 [ 0  0  0  0]]
Система имеет бесконечное множество решений


#### Методичка 2
1. Решить систему уравнений методом Крамера:

a)  
𝑥1 − 2 * 𝑥2 = 13  
𝑥1 − 4 * 𝑥2 = 7

In [711]:
def kramer(a):
    # Разделим расширенную матрицу на две
    b = np.copy(a[:,:-1])
    print('Матрица коэффициэнтов')
    print(b)
    c = np.copy(a[:,-1:].T[0])
    print('Свободные члены')
    print(c)
    if len(b) != len(c):
        print('Методом Крамера систему не решить')
        return 0, 0, 0
    elif np.linalg.det(b) == 0:
        print('Система решений не имеет')
        return 0, 0, 0
    d = np.zeros([len(b), len(b)])
    x = []
    for i in range(len(b[0])):
        b[:, i] = c
        d = np. copy(b)
        b = np.copy(a[:,:-1])
        print('Матрица A', i)
        print(d)
        x.append(np.linalg.det(d) / np.linalg.det(b))
    print('Результат')
    print(x)
    return b, c, x

In [712]:
a6 = np.array([[1, -2, 13],
              [1, -4, 7]])

In [713]:
b6, c6, x6 = kramer(a6)

Матрица коэффициэнтов
[[ 1 -2]
 [ 1 -4]]
Свободные члены
[13  7]
Матрица A 0
[[13 -2]
 [ 7 -4]]
Матрица A 1
[[ 1 13]
 [ 1  7]]
Результат
[18.999999999999996, 3.0]


In [714]:
check(b6, c6, x6)

13 = 12.999999999999996
7 = 6.9999999999999964
**********


б)  
2 * 𝑥1 − 𝑥2 + 5 * 𝑥3 = 10  
𝑥1 + 𝑥2 − 3 * 𝑥3 = −2  
2 * 𝑥1 + 4 * 𝑥2 + 𝑥3 = 1

In [715]:
a7 = np.array([[2, -1, 5, 10],
              [1, 1, -3, -2],
              [2, 4, 1, 1]])

In [716]:
b7, c7, x7 = kramer(a7)

Матрица коэффициэнтов
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Свободные члены
[10 -2  1]
Матрица A 0
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Матрица A 1
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Матрица A 2
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Результат
[2.0000000000000018, -1.0000000000000009, 1.0]


In [717]:
check(b7, c7, x7)

10 = 10.000000000000004
-2 = -1.9999999999999991
1 = 1.0
**********
